name: seco_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  google_sign_in: ^6.2.1
  fluttertoast: ^8.2.8
  cloud_firestore: ^5.4.0
  glassmorphism: ^3.0.0
  google_fonts: ^6.2.1
  motion_toast: ^2.11.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_slidable: ^3.1.1
  intl: ^0.19.0
  flutter_switch: ^0.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
