// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4_23hTLAA5dnlXMUG__-a1eYZj4B9gRg',
    appId: '1:334998744642:web:73aa5d880e7c05858647db',
    messagingSenderId: '334998744642',
    projectId: 'seco-app-86863',
    authDomain: 'seco-app-86863.firebaseapp.com',
    storageBucket: 'seco-app-86863.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtjkGwh87dRwCohVfNUxtkM0CyytVz3m8',
    appId: '1:334998744642:android:f2ed7f8b203240398647db',
    messagingSenderId: '334998744642',
    projectId: 'seco-app-86863',
    storageBucket: 'seco-app-86863.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxJ_BjJ6UpJrly4bgRly9a5g0-flJXZcI',
    appId: '1:334998744642:ios:9879b92941f411b78647db',
    messagingSenderId: '334998744642',
    projectId: 'seco-app-86863',
    storageBucket: 'seco-app-86863.appspot.com',
    iosBundleId: 'com.example.secoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxJ_BjJ6UpJrly4bgRly9a5g0-flJXZcI',
    appId: '1:334998744642:ios:9879b92941f411b78647db',
    messagingSenderId: '334998744642',
    projectId: 'seco-app-86863',
    storageBucket: 'seco-app-86863.appspot.com',
    iosBundleId: 'com.example.secoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4_23hTLAA5dnlXMUG__-a1eYZj4B9gRg',
    appId: '1:334998744642:web:c8c64a2ee5ffe6aa8647db',
    messagingSenderId: '334998744642',
    projectId: 'seco-app-86863',
    authDomain: 'seco-app-86863.firebaseapp.com',
    storageBucket: 'seco-app-86863.appspot.com',
  );
}
